language: node_js
node_js:
  - 5 
before_install:
  - npm install -g npm
script:
  - npm run build
notifications:
  email: false
sudo: false
deploy:
  on: production
  provider: surge
  project: ./build/
  domain: idappthat.surge.sh
  skip_cleanup: true



