language: node_js
node_js:
  - 5 
script:
  - npm run build
notifications:
  email: false
sudo: false
cache: 
  directories:
  - node_modules
deploy:
  on: production
  provider: surge
  project: ./build/
  domain: idappthat.surge.sh
  skip_cleanup: true



